apiVersion: v1
kind: Template
metadata:
  name: npm-validator
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: npm-validator
  spec:
    lookupPolicy:
      local: true
  status:
    dockerImageRepository: ""
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: dependency-monkey
    name: npm-validator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: npm-validator:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: feature/npm-validator
        uri: https://github.com/goern/thoth-dependency-monkey
      type: Git
      contextDir: images/npm-validator
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange