apiVersion: v1
kind: Template
metadata:
  name: thoth-dependency-monkey-buildconfig
  labels:
    template: thoth-dependency-monkey-buildconfig
    app: thoth
    component: dependency-monkey
  annotations:
    description: >
      This is Thoth Dependency Monkey API BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: Thoth Dependency Monkey API BuildConfig
    thoth-station.ninja/version: 0.3.0
    tags: poc,thoth,dependency-monkey,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Dependency Monkey API BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
      name: dependency-monkey
    spec:
      lookupPolicy:
        local: true
      name: stable

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
      name: pypi-validator
    spec:
      lookupPolicy:
        local: true
      name: stable

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: dependency-monkey
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "dependency-monkey:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
      name: pypi-validator
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "pypi-validator:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        contextDir: images/pypi-validator
      strategy:
        type: Docker

parameters:
  - description: Git repository for Thoth's Dependency Monkey API
    displayName: Thoth Dependency Monkey git repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/Thoth-Station/dependency-monkey'

  - description: Git repository for Thoth's Dependency Monkey API
    displayName: Thoth Dependency Monkey git reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
