apiVersion: v1
kind: Template
metadata:
  name: dependency-monkey
  labels:
    template: thoth-dependency-monkey-buildconfig
    app: thoth
    component: dependency-monkey
  annotations:
    description: >
      This is Thoth Dependency Monkey, it validates package dependencies in software stacks.
    openshift.io/display-name: Dependency Monkey
    thoth-station.ninja/version: 0.3.0
    tags: thoth, dependency-monkey, dependencymonkey, poc
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/dependency-monkey/
    template.openshift.io/long-description: >
      This template defines resources needed
      to deploy Thoth Dependency Monkey as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
message: |-
  For more information about using this template see https://github.com/Thoth-Station/dependency-monkey/

  You should be able to access .../openapi/ now.

  Have Fun!

objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: validation-job-runner
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
    automountServiceAccountToken: true

  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: validation-job-binding
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
    roleRef:
      kind: ClusterRole
      name: view
    subjects:
      - kind: ServiceAccount
        name: validation-job-runner

  - kind: Route
    apiVersion: v1
    metadata:
      name: dependency-monkey
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
    spec:
      to:
        kind: Service
        name: dependency-monkey

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
      name: dependency-monkey
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: dependency-monkey

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: dependency-monkey
      annotations:
        thoth-station.ninja/version: 0.3.0
      name: dependency-monkey
    spec:
      replicas: 1
      selector:
        app: thoth
        component: dependency-monkey
        deploymentconfig: dependency-monkey
      template:
        metadata:
          labels:
            app: thoth
            component: dependency-monkey
            deploymentconfig: dependency-monkey
          annotations:
            thoth-station.ninja/version: 0.3.0
        spec:
          serviceAccount: validation-job-runner
          serviceAccountName: validation-job-runner
          containers:
            - name: dependency-monkey
              from:
                kind: ImageStreamTag
                name: dependency-monkey:latest
              imagePullPolicy: Always
              serviceAccountName: validation-job-runner
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: THOTH_DEPENDENCY_MONKEY_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 256Mi
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - dependency-monkey
            from:
              kind: ImageStreamTag
              name: 'dependency-monkey:latest'
